name: Web Extension

on:
  push:
    paths:
      - 'webextension/**'
    branches-ignore:
      - "dependabot/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - "!dependabot/**"

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Update packages list
        run: sudo apt update

      - name: Install rename
        run: sudo apt install rename

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Package webextensions
        run: npm run webext
